DROP TABLE IF EXISTS OrderContains;
DROP TABLE IF EXISTS CartContains;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Users;

CREATE TABLE Inventory(
    PROD_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROD_NAME VARCHAR(64),
	PROD_DESC VARCHAR(512) DEFAULT 'Empty Product Description',
	IMG_URL VARCHAR(128) DEFAULT '',
    PROD_QTY INT,
    PROD_TYPE VARCHAR(32),
    PRICE DECIMAL(8,2)
);

CREATE TABLE Users(
    USER_IDX VARCHAR(32) PRIMARY KEY,
    USER_PASS VARCHAR(32) NOT NULL,
    IS_OWNER BOOL DEFAULT FALSE,
    IS_EMPLOYEE BOOL DEFAULT FALSE
);

CREATE TABLE Orders(
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID VARCHAR(32),
    ORDER_STATUS VARCHAR(32),
	CONTACT_EMAIL VARCHAR(32),
    SHIPPING_ADDRESS VARCHAR(64),
    BILLING_ADDRESS VARCHAR(64),
    CREDIT_CARD_NUM BIGINT,
    CVV_NUM INT,
	ORDER_NOTE VARCHAR(256),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES Users(USER_IDX)
);

CREATE TABLE OrderContains(
    ORDER_ID INT,
    PROD_ID INT,
    ORDER_QTY INT,
    PRIMARY KEY(PROD_ID, ORDER_ID),
    FOREIGN KEY(PROD_ID) REFERENCES Inventory(PROD_ID),
    FOREIGN KEY(ORDER_ID) REFERENCES Orders(ORDER_ID)
);

CREATE TABLE CartContains(
    CUSTOMER_ID VARCHAR(32),
    PROD_ID INT,
    ORDER_QTY INT,
    PRIMARY KEY(PROD_ID, CUSTOMER_ID),
    FOREIGN KEY(PROD_ID) REFERENCES Inventory(PROD_ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES Users(USER_IDX)
);