DROP TABLE IF EXISTS OrderContains;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Inventory(
    PROD_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROD_NAME VARCHAR(32),
    PROD_QTY INT,
    PRICE DECIMAL(5,2)
);

CREATE TABLE Customers(
    CUSTOMER_ID VARCHAR(32) PRIMARY KEY,
    CUSTOMER_PASS VARCHAR(32) NOT NULL
);

CREATE TABLE Orders(
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID VARCHAR(32),
    ORDER_STATUS VARCHAR(32),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES Customers(CUSTOMER_ID)
);

CREATE TABLE OrderContains(
	ORDER_ID INT,
    PROD_ID INT,
    ORDER_QTY INT,
    PRIMARY KEY(PROD_ID, ORDER_ID),
    FOREIGN KEY(PROD_ID) REFERENCES Inventory(PROD_ID),
    FOREIGN KEY(ORDER_ID) REFERENCES Orders(ORDER_ID)
);

CREATE TABLE Employees(
    EMP_ID VARCHAR(32) PRIMARY KEY,
    EMP_PASS VARCHAR(32) NOT NULL,
	IS_OWNER BOOL DEFAULT FALSE
);